# https://github.com/Yikun/hub-mirror-action
name: SyncToGitee
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/starfishs'    					
          dst: 'gitee/goohappy'     					
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  	
          dst_token:  ${{ secrets.GITEE_TOKEN }}     	
          force_update: true
          static_list: "sql2struct"   					
          debug: true
